//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18444
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------
using NUnit.Framework;
using System;
using Toast.Iap.Ongate;

[TestFixture()]
public class ToastIAPTest
{
	[SetUp]
	public void Init()
	{

	}

	[Test()]
	public void SetDebugModeTest()
	{
        ToastIapOngate.SetDebugMode(true);
	}

	[Test()]
	public void RegisterUserIdTest()
	{
		Result result = ToastIapOngate.SetOngateUserId("unity_user001");
		Assert.AreEqual("unity_user001", result.ResultString);
	}

	[Test()]
	public void RequestPurchase()
	{
        ToastIapOngate.Purchase("1000001", (Result result, object data) => {

		});		
	}

	[Test()]
	public void QueryPurchases()
	{
        ToastIapOngate.RequestConsumablePurchases((Result result, object data) => {
			
		});		
	}
}